version: '3.8'
services:

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/opt/app/redis/data
    networks:
      - movies-api-network
    restart: on-failure

  postgres:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./db/init_multitype_db.sh:/docker-entrypoint-initdb.d/init_multitype_db.sh
    networks:
      - movies-api-network
    restart: on-failure

  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    logging:
      driver: none
    networks:
      - movies-api-network
    restart: on-failure

networks:
  movies-api-network:
    name: movies-api-network
    driver: bridge

volumes:
  postgresdata:
  redis-data: