version: '3.8'
services:

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/opt/app/redis/data
    networks:
      - movies-api-network
    restart: on-failure

  postgres:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./db/init_multitype_db.sh:/docker-entrypoint-initdb.d/init_multitype_db.sh
    networks:
      - movies-api-network
    restart: on-failure

  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    logging:
      driver: none
    networks:
      - movies-api-network
    restart: on-failure

  order_scheduler:
    build:
      context: ./order_service
      dockerfile: DockerFile-scheduler
    depends_on:
      - rabbit
    networks:
      - movies-api-network

  order_worker:
    build:
      context: ./order_service
      dockerfile: Dockerfile-worker
    depends_on:
      - rabbit
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
    networks:
      - movies-api-network

  payment_scheduler:
    build:
      context: ./payment_service
      dockerfile: DockerFile-scheduler
    depends_on:
      - rabbit
    networks:
      - movies-api-network

  payment_worker:
    build:
      context: ./payment_service
      dockerfile: Dockerfile-worker
    depends_on:
      - rabbit
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
    networks:
      - movies-api-network

networks:
  movies-api-network:
    name: movies-api-network
    driver: bridge

volumes:
  postgresdata:
  redis-data: