version: '3.8'
services:

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    ports:
      - "5432:5432"
    env_file:
      - dev.env

  redis:
    extends:
      file: docker-compose.yaml
      service: redis

  rabbit:
    extends:
      file: docker-compose.yaml
      service: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  movies-api-network:
    name: movies-api-network
    driver: bridge

volumes:
  postgresdata:
  redis-data: