version: '3.8'
services:

  redis:
    extends:
      file: docker-compose.yaml
      service: redis

  postgres:
    environment:
      - POSTGRES_MULTIPLE_DBS
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    extends:
      file: docker-compose.yaml
      service: postgres

  rabbit:
    extends:
      file: docker-compose.yaml
      service: rabbit

  order_scheduler:
    extends:
      file: docker-compose.yaml
      service: order_scheduler

  order_worker:
    extends:
      file: docker-compose.yaml
      service: order_worker

  payment_scheduler:
    extends:
      file: docker-compose.yaml
      service: payment_scheduler

  payment_worker:
    extends:
      file: docker-compose.yaml
      service: payment_worker

networks:
  movies-api-network:
    name: movies-api-network
    driver: bridge

volumes:
  postgresdata:
  redis-data: